# Change these first
owner: RDLGBC # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: RDLABS
    url: https://www.rdlabs.science/
  - name: RDL
    url: https://www.rdl.science/
  - name: RespirVent
    url: https://www.respirvent.com/
  - name: Doyle Dynamics
    url: http://www.doyledynamics.com/
  - name: R&D Lab Inc.
    url: http://rdlabinc.com
 
  - name: Authoritative DNS Provider - Cloudflare
  - name: Public DNS Resolver - Cloudflare
    url: https://1.1.1.1

 
  - name: Cloudflare
    url: https://www.cloudflare.com
  - name: Cloudflare Pages
    url: https://pages.cloudflare.com/
  - name: GitHub
    url: https://github.com
  - name: Google
    url: https://www.google.com
  - name: Bing
    url: https://www.bing.com
  - name: Facebook
    url: https://www.facebook.com
  - name: Wikipedia
    url: https://en.wikipedia.org

  - name: DNS TLD com - a.gtld-servers.net
    url: http://192.5.6.30
  - name: DNS TLD com - b.gtld-servers.net
    url: http://192.33.14.30
  - name: DNS TLD com - c.gtld-servers.net
    url: http://192.26.92.30
  - name: DNS TLD com - d.gtld-servers.net
    url: http://192.31.80.30
  - name: DNS TLD com - e.gtld-servers.net
    url: http://192.12.94.30
  - name: DNS TLD com - f.gtld-servers.net
    url: http://192.35.51.30
  - name: DNS TLD com - g.gtld-servers.net
    url: http://192.42.93.30
  - name: DNS TLD com - h.gtld-servers.net
    url: http://192.54.112.30
  - name: DNS TLD com - i.gtld-servers.net
    url: http://192.43.172.30
  - name: DNS TLD com - j.gtld-servers.net
    url: http://192.48.79.30
  - name: DNS TLD com - k.gtld-servers.net
    url: http://192.52.178.30
  - name: DNS TLD com - l.gtld-servers.net
    url: http://192.41.162.30
  - name: DNS TLD com - m.gtld-servers.net
    url: http://192.55.83.30

  - name: DNS Root Server - A - Verisign Inc
    url: http://198.41.0.4
    - name: DNS Root Server - B
    url: http://199.9.14.201
    - name: DNS Root Server - C
    url: http://192.33.4.12
    - name: DNS Root Server - D
    url: http://199.7.91.13
    - name: DNS Root Server - E
    url: http://192.203.230.10
    - name: DNS Root Server - F
    url: http://195.5.5.241
    - name: DNS Root Server - G
    url: http://192.112.36.4
    - name: DNS Root Server - H
    url: http://198.97.190.53
    - name: DNS Root Server - I
    url: http://192.36.148.17
    - name: DNS Root Server - J
    url: http://192.58.128.30
    - name: DNS Root Server - K
    url: http://193.0.14.129
    - name: DNS Root Server - L
    url: http://199.7.83.42
    - name: DNS Root Server - M
    url: http://202.12.27.33

assignees:
  - RDLGBC

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
